import { GoogleGenAI, Modality } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const model = 'gemini-2.5-flash-image-preview';

export interface ImageInput {
    base64: string;
    mimeType: string;
}

export const generateImage = async (prompt: string, images: ImageInput[]): Promise<string> => {
    try {
        const imageParts = images.map(image => ({
            inlineData: {
                data: image.base64,
                mimeType: image.mimeType,
            },
        }));

        const textPart = { text: prompt };

        const response = await ai.models.generateContent({
            model: model,
            contents: {
                parts: [...imageParts, textPart],
            },
            config: {
                responseModalities: [Modality.IMAGE, Modality.TEXT],
            },
        });
        
        const candidate = response.candidates?.[0];
        
        if (!candidate) {
             // This can happen if the prompt itself is blocked.
             const promptFeedback = response.promptFeedback;
             let reason = "Unknown reason";
             if (promptFeedback?.blockReason) {
                 reason = `Prompt was blocked due to: ${promptFeedback.blockReason}`;
             }
             throw new Error(`The request was blocked and no content was generated. ${reason}`);
        }

        const imagePart = candidate.content?.parts?.find(part => part.inlineData);

        if (imagePart?.inlineData) {
            const base64ImageBytes = imagePart.inlineData.data;
            return `data:${imagePart.inlineData.mimeType};base64,${base64ImageBytes}`;
        } else {
            // If no image, construct a detailed error message
            let errorMessage = "No image was generated by the API.";
            const finishReason = candidate.finishReason;
            
            if (finishReason && finishReason !== 'STOP') {
                errorMessage += ` The process stopped because: ${finishReason}.`;
            }

            const textPart = candidate.content?.parts?.find(part => part.text);
            if (textPart?.text) {
                errorMessage += ` The model responded with: "${textPart.text.trim()}"`;
            }

            // For debugging, it's good to log the whole response if things go wrong
            console.error("Image generation failed. Full API response:", response);

            throw new Error(errorMessage);
        }

    } catch (error) {
        console.error('Error calling Gemini API:', error);
        // Re-throw a user-friendly error
        if (error instanceof Error) {
            throw new Error(`Failed to generate image. Reason: ${error.message}`);
        }
        throw new Error('Failed to generate image due to an unknown error. Please check the console.');
    }
};