// This file contains base64 encoded virtual backgrounds to be used in the image editor.
// Using base64 strings makes the backgrounds self-contained within the application.
// For a real-world app, these might be loaded from a CDN for better performance.

interface VirtualBackground {
    name: string;
    data: string; // base64 encoded image data
    mime: string; // e.g., 'image/jpeg'
}

export const virtualBackgrounds: VirtualBackground[] = [
    {
        name: 'Urban Street',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEXo5ubr6+vQp3FBAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Beach Sunset',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEVUdM//zADb/VfWAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Forest Path',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEU6OOuIg/Tq38dAAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Studio White',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEV/f3+AgIBa2e4TAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Neon City',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEUiHxPNEB1y7aLqAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Cafe Interior',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEVMaXH///9GP7OIAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Mountain Top',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEVEQkLp6ekGjN8SAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Library',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEX///8lJSU4nH5AAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
    {
        name: 'Art Gallery',
        mime: 'image/png',
        data: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMgAQMAAADjpC33AAAABlBMVEWkpKS2trbplOYoAAAAAXRSTlMAQObYZgAAAIlJREFUeNrtwTEBAAAAwiD7p/ZZDG/gAAAAAAAAAAAAAAA+Bq4gEAAQ8BoIAADgNWAAgAABAwAIACBgAQAEBAwAIAADBgAQAEAAAwAIAAEBAwAIAAEAAAwAIAAAQMACAAAYAEAAAwAIACBgAQAEAAAwAIACBgAQAEBAwAIAAAQMACAAAYAEBAwAIAADgNWAAgAABAwAIACBgL24An7Ie670AAAAASUVORK5CYII=',
    },
];